
var works = [
["Ability", "Способность"],
["Accounting", "Учет"],
["Addition", "Дополнение"],
["Adequate", "Адекватное"],
["Administrator", "Администратор"],
["Advance", "Аванс"],
["Analysis", "Анализ"],
["Analysts", "Аналитики"],
["Analyze", "Анализ"],
["Annual", "Ежегодный"],
["Application", "Приложение"],
["Architect", "Архитектор"],
["Area", "Область"],
["Arise", "Встать"],
["Associate", "Партнер, Ассоциированный, Ассоциировать"],
["Background", "Фон"],
["Business", "Бизнес"],
["Carpal", "Карпал"],
["Carrier", "Перевозчик"],
["Certification", "Сертификация"],
["Chapter", "Глава"],
["Chief", "Начальник"],
["Code", "Код, Кодировать"],
["Common", "Общий"],
["Communicate", "Общение"],
["Communication", "Общение"],
["Competitive", "Конкурентный"],
["Computer", "Компьютер"],
["Computing", "Вычисления, вычислять"],
["Concentrate", "Концентрат, Сконцентрировать"],
["Considerable", "Значительное"],
["Consultant", "Консультант"],
["Consulting", "Консалтинг"],
["Coordinate", "Координата"],
["Create", "Создать"],
["Customer", "Клиент"],
["Cyber", "Кибер"],
["Data", "Данные"],
["Database", "База данных"],
["Deal", "Сделка, Договориться"],
["Decline", "Отклонение"],
["Demand", "Спрос, Требовать"],
["Design", "Дизайн"],
["Designer", "Дизайнер"],
["Detailed", "Подробное"],
["Determine", "Определить"],
["Developer", "Разработчик"],
["Development", "Развитие"],
["Discussion", "Обсуждение"],
["Effectively", "Эффективно"],
["Efficiency", "Эффективность"],
["Electronic", "Электронная"],
["Employ", "Работать"],
["Engineering", "Инженерное дело"],
["Engineer", "Инженер"],
["Enterprise", "Предприятие"],
["Environment", "Окружающая среда"],
["Equipment", "Оборудование"],
["Expertise", "Экспертиза"],
["Finance", "Финансы"],
["Financia", "Финансовый"],
["Firm", "Фирма"],
["Force", "Сила, Заставлять"],
["Function", "Функция"],
["Goal", "Цель"],
["Graduate", "Выпускник"],
["Hardware", "Оборудование"],
["Implementation", "Реализация"],
["Install", "Установить"],
["Institution", "Учреждение"],
["Instruction", "Инструкция"],
["Insurance", "Страхование"],
["Integrate", "Интеграция"],
["Intranet", "Интранет"],
["Introductory", "Вводный"],
["Involved", "Участие"],
["Keyboard", "Клавиатура"],
["Knowledge", "Знание"],
["Laboratory", "Лаборатория"],
["Language", "Язык"],
["Latest", "Последнее"],
["Lead", "Свинец, Вести"],
["Leadership", "Лидерство"],
["Level", "Уровень"],
["Location", "Местонахождение"],
["Lowest", "Самый низкий"],
["Maintain", "Поддержание"],
["Maintenance", "Техническое обслуживание"],
["Marketing", "Маркетинг"],
["Mathematics", "Математика"],
["Matrix", "Матрица"],
["Median", "Медиана"],
["Mobile", "Мобильный"],
["Monitor", "Монитор, Контролировать"],
["Nature", "Природа"],
["Network", "Сеть"],
["Officer", "Офицер"],
["Office", "Офис"],
["Offshore", "Оффшор"],
["Order", "Порядок"],
["Organization", "Организация"],
["Outsourcing", "Аутсорсинг"],
["Oversee", "Наблюдать"],
["Perform", "Выполнить"],
["Performance", "Производительность"],
["Period", "Период"],
["Plan", "План, Планировать"],
["Prevailing", "Превалирующий"],
["Problem", "Проблема"],
["Process", "Процесс, Обрабатывать"],
["Product", "Продукт"],
["Program", "Программа, Программировать"],
["Programmer", "Программист"],
["Project", "Проект"],
["Projections", "Прогнозы"],
["Promoted", "Продвижение"],
["Prospect", "Проспект"],
["Provide", "Предоставить"],
["Publishing", "Издательская деятельность"],
["Rapid", "Быстрый"],
["Reduce", "Уменьшить"],
["Relevant", "Релевантный, Соответствующий"],
["Remote", "Удаленный"],
["Replace", "Заменить"],
["Research", "Исследования, Исследовать"],
["Resource", "Ресурс"],
["Respond", "Ответ"],
["Rounded", "Округленное"],
["Sales", "Продажи"],
["Science", "Наука"],
["Scientific", "Научно"],
["Scientist", "Ученый"],
["Section", "Раздел"],
["Security", "Безопасность"],
["Service", "Служба"],
["Simultaneously", "Одновременно"],
["Site", "Сайт"],
["Software", "Программное обеспечение"],
["Sophisticated", "Сложный"],
["Specialist", "Специалист"],
["Specialized", "Специализированный"],
["Specific", "Специфический"],
["Spend", "Тратить"],
["Staff", "Персонал"],
["Statistic", "Статистика"],
["Substantial", "Существенное"],
["Sufficient", "Достаточно"],
["Support", "Поддержка"],
["Syndrome", "Синдром"],
["System", "Система"],
["Task", "Задача"],
["Technical", "Техническое"],
["Technician", "Техник"],
["Technological", "Технологический"],
["Technology", "Технология"],
["Telecommunications", "Телекоммуникации"],
["Title", "Название"],
["Tool", "Инструмент"],
["Training", "Тренировка"],
["Transfer", "Перенос, Передавать"],
["Uncommon", "Необычный"],
["Understanding", "Понимание"],
["User", "Пользователь"],
["Variety", "Разнообразие"],
["Vendor", "Поставщик"],
["Webmaster", "Веб-мастер"],
["Wireless", "Беспроводная связь"],
["Worker", "Работник"],
["Workplace", "Рабочее место"],]
